In [4]:
import numpy as np

import logbook

import sys

In [5]:
logbook.StreamHandler(sys.stdout).push_application()
logger = logbook.Logger('logbook')

In [86]:
stars1 = np.random.random(1000) * 100
stars2 = np.random.random(1000) * 100
stars = np.zeros((1000, 2))

In [87]:
stars[:, 0] = stars1
stars[:, 1] = stars2

In [88]:
# stars

In [89]:
logger.info('The input image data converted to CCDData.')

[2019-09-02 02:23:39.680844] INFO: logbook: The input image data converted to CCDData.


In [90]:
stars.shape[0]

1000

In [91]:
stars[1]

array([38.9638893 , 29.44608798])

In [92]:
def dis_mes(stars):
    distances = np.zeros((stars.shape[0], stars.shape[0]))
    logger.info('Start')
    for i in range(stars.shape[0]):
        if i < stars.shape[0] - 1:
            dis1 = stars[i,0] - stars[i + 1:, 0]
#             print(dis1)
            dis2 = stars[i,1] - stars[i + 1:, 1]
            dis = np.sqrt(dis1 ** 2 + dis2 **2)
            distances[i][i + 1:] = dis
    logger.info('The End!')
    return distances

In [93]:
dism = dis_mes(stars)

[2019-09-02 02:23:41.735493] INFO: logbook: Start
[2019-09-02 02:23:41.761274] INFO: logbook: The End!


In [71]:
dism

array([[ 0.        , 50.64620176, 22.49535396, 83.97020845, 54.4955434 ],
       [ 0.        ,  0.        , 28.40551594, 50.6745798 , 37.95879547],
       [ 0.        ,  0.        ,  0.        , 68.4374336 , 43.05268607],
       [ 0.        ,  0.        ,  0.        ,  0.        , 30.98033196],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]])

In [53]:
dis1 = stars[0,0]  - stars[0 + 1:, 0] 

In [54]:
dis1.shape

(4,)

In [55]:
dis1

array([-50.32216916, -22.49534871, -63.82823551, -36.02998698])

In [56]:
distances = np.zeros((100, 100))

In [57]:
distances

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [58]:
distances[0][2:].shape

(98,)

In [59]:
dism = dis_mes(stars)